-- begin QRCODE_EVENT_REQUEST
alter table QRCODE_EVENT_REQUEST add constraint FK_QRCODE_EVENT_REQUEST_ON_EVENT_HALL foreign key (EVENT_HALL_ID) references QRCODE_HALL(ID)^
create index IDX_QRCODE_EVENT_REQUEST_ON_EVENT_HALL on QRCODE_EVENT_REQUEST (EVENT_HALL_ID)^
-- end QRCODE_EVENT_REQUEST
-- begin QRCODE_EVENT_PARTICIPANT
alter table QRCODE_EVENT_PARTICIPANT add constraint FK_QRCODE_EVENT_PARTICIPANT_ON_EVENT_REQUEST foreign key (EVENT_REQUEST_ID) references QRCODE_EVENT_REQUEST(ID)^
alter table QRCODE_EVENT_PARTICIPANT add constraint FK_QRCODE_EVENT_PARTICIPANT_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_QRCODE_EVENT_PARTICIPANT_ON_EVENT_REQUEST on QRCODE_EVENT_PARTICIPANT (EVENT_REQUEST_ID)^
create index IDX_QRCODE_EVENT_PARTICIPANT_ON_USER on QRCODE_EVENT_PARTICIPANT (USER_ID)^
-- end QRCODE_EVENT_PARTICIPANT
-- begin QRCODE_EVENT_EXTERNAL_PARTICIPANT
alter table QRCODE_EVENT_EXTERNAL_PARTICIPANT add constraint FK_QRCODE_EVENT_EXTERNAL_PARTICIPANT_ON_EVENT_REQUEST foreign key (EVENT_REQUEST_ID) references QRCODE_EVENT_REQUEST(ID)^
alter table QRCODE_EVENT_EXTERNAL_PARTICIPANT add constraint FK_QRCODE_EVENT_EXTERNAL_PARTICIPANT_ON_GUEST foreign key (GUEST_ID) references QRCODE_EXTERNAL_GUEST(ID)^
create index IDX_QRCODE_EVENT_EXTERNAL_PARTICIPANT_ON_EVENT_REQUEST on QRCODE_EVENT_EXTERNAL_PARTICIPANT (EVENT_REQUEST_ID)^
create index IDX_QRCODE_EVENT_EXTERNAL_PARTICIPANT_ON_GUEST on QRCODE_EVENT_EXTERNAL_PARTICIPANT (GUEST_ID)^
-- end QRCODE_EVENT_EXTERNAL_PARTICIPANT
-- begin QRCODE_RECIPIENT_LIST
alter table QRCODE_RECIPIENT_LIST add constraint FK_QRCODE_RECIPIENT_LIST_ON_OWNER foreign key (OWNER_ID) references SEC_USER(ID)^
create index IDX_QRCODE_RECIPIENT_LIST_ON_OWNER on QRCODE_RECIPIENT_LIST (OWNER_ID)^
-- end QRCODE_RECIPIENT_LIST
-- begin QRCODE_RECIPIENT_LIST_USER_LINK
alter table QRCODE_RECIPIENT_LIST_USER_LINK add constraint FK_RECLISUSE_ON_RECIPIENT_LIST foreign key (RECIPIENT_LIST_ID) references QRCODE_RECIPIENT_LIST(ID)^
alter table QRCODE_RECIPIENT_LIST_USER_LINK add constraint FK_RECLISUSE_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
-- end QRCODE_RECIPIENT_LIST_USER_LINK
-- begin QRCODE_RECIPIENT_LIST_SHARE_LINK
alter table QRCODE_RECIPIENT_LIST_SHARE_LINK add constraint FK_RECLISSHA_ON_RECIPIENT_LIST foreign key (RECIPIENT_LIST_ID) references QRCODE_RECIPIENT_LIST(ID)^
alter table QRCODE_RECIPIENT_LIST_SHARE_LINK add constraint FK_RECLISSHA_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
-- end QRCODE_RECIPIENT_LIST_SHARE_LINK
-- begin QRCODE_REQUEST_USER_LINK
alter table QRCODE_REQUEST_USER_LINK add constraint FK_REQUSE_ON_REQUEST foreign key (REQUEST_ID) references QRCODE_REQUEST(ID)^
alter table QRCODE_REQUEST_USER_LINK add constraint FK_REQUSE_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
-- end QRCODE_REQUEST_USER_LINK
