alter table QRCODE_RECIPIENT_COMPANY_LIST add constraint FK_QRCODE_RECIPIENT_COMPANY_LIST_ON_OWNER foreign key (OWNER_ID) references SEC_USER(ID);
create index IDX_QRCODE_RECIPIENT_COMPANY_LIST_ON_OWNER on QRCODE_RECIPIENT_COMPANY_LIST (OWNER_ID);
