alter table QRCODE_EVENT_PARTICIPANT add constraint FK_QRCODE_EVENT_PARTICIPANT_ON_EVENT_REQUEST foreign key (EVENT_REQUEST_ID) references QRCODE_EVENT_REQUEST(ID);
alter table QRCODE_EVENT_PARTICIPANT add constraint FK_QRCODE_EVENT_PARTICIPANT_ON_USER foreign key (USER_ID) references SEC_USER(ID);
create index IDX_QRCODE_EVENT_PARTICIPANT_ON_EVENT_REQUEST on QRCODE_EVENT_PARTICIPANT (EVENT_REQUEST_ID);
create index IDX_QRCODE_EVENT_PARTICIPANT_ON_USER on QRCODE_EVENT_PARTICIPANT (USER_ID);
