alter table QRCODE_EVENT_REQUEST add constraint FK_QRCODE_EVENT_REQUEST_ON_EVENT_HALL foreign key (EVENT_HALL_ID) references QRCODE_HALL(ID);
create index IDX_QRCODE_EVENT_REQUEST_ON_EVENT_HALL on QRCODE_EVENT_REQUEST (EVENT_HALL_ID);
