alter table QRCODE_TEXT_TEMPLATE add constraint FK_QRCODE_TEXT_TEMPLATE_ON_OWNER foreign key (OWNER_ID) references SEC_USER(ID);
alter table QRCODE_TEXT_TEMPLATE add constraint FK_QRCODE_TEXT_TEMPLATE_ON_CATEGORY foreign key (CATEGORY_ID) references QRCODE_TEMPLATE_CATEGORIES(ID);
create index IDX_QRCODE_TEXT_TEMPLATE_ON_OWNER on QRCODE_TEXT_TEMPLATE (OWNER_ID);
create index IDX_QRCODE_TEXT_TEMPLATE_ON_CATEGORY on QRCODE_TEXT_TEMPLATE (CATEGORY_ID);
