alter table QRCODE_RECIPIENT_LIST add constraint FK_QRCODE_RECIPIENT_LIST_ON_OWNER foreign key (OWNER_ID) references SEC_USER(ID);
create index IDX_QRCODE_RECIPIENT_LIST_ON_OWNER on QRCODE_RECIPIENT_LIST (OWNER_ID);
