alter table QRCODE_TEMPLATE_CATEGORIES add constraint FK_QRCODE_TEMPLATE_CATEGORIES_ON_OWNER foreign key (OWNER_ID) references SEC_USER(ID);
create index IDX_QRCODE_TEMPLATE_CATEGORIES_ON_OWNER on QRCODE_TEMPLATE_CATEGORIES (OWNER_ID);
